#ifndef _FREQUENCIES_H_
#define _FREQUENCIES_H_

#define BMS_HEARTBEAT_FREQUENCY 1
#define PDM_HEARTBEAT_FREQUENCY 10
#define THROTTLE_HEARTBEAT_FREQUENCY 10
#define VELOCITY_HEARTBEAT_FREQUENCY 5

#endif
